### ISSUE TITLE
Presssing enter when asked to create new id takes you to signup

### ISSUE THREAD

**Issue by Mohammad-Hamzah** [infrared-o8/hospital-management-python-sql#4]
![image](https://github.com/user-attachments/assets/bd8a4fcb-9946-461c-897f-cbf627867f49)
idk if this is intentional or not but if you press enter here (this is what i did) it takes you to signup

**Comment by infrared-o8** [comment]
i'll implement error handling for all inputs in the code.

**Comment by infrared-o8** [comment]
with cinput, all the inputs should be handled properly now
