### ISSUE TITLE
Cant signup as admin

### ISSUE THREAD

**Issue by Mohammad-Hamzah** [infrared-o8/hospital-management-python-sql#5]
![image](https://github.com/user-attachments/assets/cf589fcd-f768-458b-a53f-25dcdc1c087e)
I logged in with an existing admin account and then approved sign up for a new account i was trying... then i tried to signup and it said create new password? then i selected yes but it sent me back

**Comment by infrared-o8** [comment]
i was missing an int in the input for the 'User was found with no password...'. should be fixed now, thanks!

**Comment by Mohammad-Hamzah** [comment]
![image](https://github.com/user-attachments/assets/aa6b2dea-3a99-4089-a550-54be415d4e59)
it does ask for password now but keeps doing that forever seems like a while loop problem

**Comment by infrared-o8** [comment]
the while loop im using here checks if the password is null or empty, and if it is, keeps on asking for the password until it gets a non-null value. are you entering a value? if yes, then i need to check the logic again...

**Comment by infrared-o8** [comment]
the bug should be fixed. it was incorrect logic 😭
thankss

**Comment by Mohammad-Hamzah** [comment]
😭 
![image](https://github.com/user-attachments/assets/4da856b7-030d-4211-b5e2-ded4c00c57c1)
idk why dis acts weird after it asked password and all it took me back to start then i can login through the id only if i click signup as you can see... if i click login it says doesnt exist 😭

**Comment by infrared-o8** [comment]
oh yea when it asks for your adminID, you should give adm10 in ur case.

irl, a person would have his badge with him, containing the id, name, etc. that's why I'm asking for ID and not name in login, cuz people can have duplicate names

**Comment by infrared-o8** [comment]
try it now using adm10 for enter admin id

**Comment by Mohammad-Hamzah** [comment]
it works 🥹
